# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation
{{- if eq .Values.enableDbAuth true }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: emco
  labels:
    app: mongo
type: kubernetes.io/basic-auth
data:
  username: {{ default "" .Values.db.emcoUser | b64enc  | quote }}
  password: {{ default "" .Values.db.emcoPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-secret
  namespace: emco
  labels:
    app: etcd
type: kubernetes.io/basic-auth
data:
  username: {{ default "" .Values.contextdb.emcoUser | b64enc  | quote }}
  password: {{ default "" .Values.contextdb.emcoPassword | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: etcd-root-secret
  namespace: emco
  labels:
    app: etcd
type: kubernetes.io/basic-auth
data:
  username: {{ default "" .Values.contextdb.rootUser | b64enc  | quote }}
  password: {{ default "" .Values.contextdb.rootPassword | b64enc | quote }}
{{- end }}
