{{/*
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation
*/}}
{{- if .Values.global.enableMongoSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-data-secret
  namespace: {{ include "common.namespace" . }}
  labels:
    app: {{ include "common.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  key: {{ (default (randAlphaNum 32) $.Values.global.db.dataSecret) | b64enc | quote }}
{{- end -}}
