resources:
  - name: provider
  - name: cluster
    parent: clusterProvider
  - name: clusterLabel
    parent: cluster
  - name: clusterKv
    parent: cluster
  - name: providerNetwork
    parent: clusterrr
  - name: network
    parent: cluster
