# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation

apiVersion: v2
appVersion: 1.1.0
description: A Helm chart for xstream-server to be deployed on app namespace
name: xstream-server
type: application
version: 0.1.0
