# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation
xstreamservice:
  ports:
  - name: service
    port: 9111
    targetPort: 9111
  server:
    port: 9111
    image:
      repository: <docker-registry-url>/xstream-server
      tag: "1.0"
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 200m
        memory: 180Mi
  type: ClusterIP
