# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation
registryPrefix:
tag: latest

workingDir: /opt/emco/monitor
git:
  enabled: false
  username: test
  token: test
  repo: test

noProxyHosts: ""
httpProxy: ""
httpsProxy: ""
