# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      collector: collectd
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        collector: collectd
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | trim | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | trim | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
{{- if .Values.env }}
          env:
{{ toYaml .Values.env | trim | indent 10 }}
{{- end  }}
{{- if .Values.command }}
          command:
{{ toYaml .Values.command | trim | indent 10 }}
{{- end  }}
{{- if .Values.args }}
          args:
{{ toYaml .Values.args | trim | indent 10 }}
{{- end  }}
          volumeMounts:
          - name: {{ template "fullname" . }}-config
            mountPath: {{ .Values.configMountPath }}
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | trim | indent 10 }}
{{- end }}
          resources:
{{- toYaml .Values.resources | trim | indent 12}}
      volumes:
      - name: {{ template "fullname" . }}-config
        configMap:
          name: {{ template "fullname" . }}-config
          defaultMode: 0744
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumes | indent 6 }}
{{- end }}
