# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
kind: Service
metadata:
  name: collectd
  labels:
    app: collectd
    release: {{ .Release.Name }}
spec:
  ports:
  - name: collectd-prometheus
    port: {{ .Values.collectd_prometheus.service.port }}
    protocol: TCP
    targetPort: {{ .Values.collectd_prometheus.service.targetPort }}
  selector:
{{ include "rangeskipempty" .Values.collectd_prometheus.service.selector | indent 4 }}
  type: ClusterIP
