apiVersion: apps/v1
kind: Deployment
metadata:
  name: tm1-nginx
  namespace: default
  labels:
    sfc: tm1-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      sfc: tm1-nginx
  template:
    metadata:
      labels:
        sfc: tm1-nginx
    spec:
      containers:
      - name: nginx
        image: rkamudhan/netshoot:v1.0
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        resources:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "128Mi"
          cpu: "500m"
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
