# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2022 Intel Corporation

apiVersion: v2
description: EMCO Distributed Traffic Controller
name: dtc
type: application
version: 1.0.0

dependencies:
  - name: common
    version: ~1.x-0
    repository: 'file://../common'